spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 1s
      lettuce:
        pool:
          max-active: 32
          max-idle: 16
          min-idle: 4
server:
  port: ${SERVER_PORT:8080}
