package com.demo.engine

import java.nio.charset.StandardCharsets
import java.security.MessageDigest
import java.util.UUID

import org.apache.hadoop.fs.{FileAlreadyExistsException, FileContext, FileSystem, Options, Path}
import org.apache.spark.sql.DataFrame
import org.apache.spark.storage.StorageLevel

import scala.util.control.NonFatal

/** Atomic directory-commit protocol shared by every durable store in this engine.
  *
  * A commit writes a UUID attempt directory, stamps it with a manifest carrying the row count and
  * a SHA-256 inventory of every Parquet file, then renames it into place non-overwritingly.
  * Requires a filesystem with atomic, non-overwriting directory rename semantics (local/HDFS
  * through Hadoop FileContext).
  */
object CommitProtocol {

  val CommitMarker = "_COMMITTED"

  final case class ArchiveFileIdentity(path: String, size: Long, sha256: String)

  def writeDirectory(
      df: DataFrame,
      attemptsRoot: Path,
      finalPath: Path,
      partitionByDate: Boolean,
      description: String,
      expectedManifest: String
  ): Unit = {
    val configuration = df.sparkSession.sparkContext.hadoopConfiguration
    val fileSystem = finalPath.getFileSystem(configuration)
    val wasPersisted = df.storageLevel != StorageLevel.NONE
    val stable = df.persist(StorageLevel.MEMORY_AND_DISK_SER)
    try {
      val rowCount = stable.count()
      if (fileSystem.exists(finalPath)) {
        validateDataCommitted(fileSystem, finalPath, expectedManifest, Some(rowCount))
        return
      }

      val attemptPath = new Path(attemptsRoot, UUID.randomUUID().toString)
      try {
        if (rowCount == 0L) {
          fileSystem.mkdirs(attemptPath)
          fileSystem.create(new Path(attemptPath, "_SUCCESS"), false).close()
        } else {
          val writer = stable.write.mode("errorifexists")
          if (partitionByDate) writer.partitionBy("date").parquet(attemptPath.toString)
          else writer.parquet(attemptPath.toString)
        }
        writeManifest(fileSystem, attemptPath,
          dataManifest(expectedManifest, rowCount, parquetInventory(fileSystem, attemptPath)))

        fileSystem.mkdirs(finalPath.getParent)
        val context = FileContext.getFileContext(fileSystem.getUri, configuration)
        try {
          context.rename(
            fileSystem.makeQualified(attemptPath),
            fileSystem.makeQualified(finalPath),
            Options.Rename.NONE
          )
        } catch {
          case _: FileAlreadyExistsException =>
            // Only this UUID attempt belongs to us; leave all sibling attempts untouched.
            fileSystem.delete(attemptPath, true)
        }

        if (!fileSystem.exists(finalPath))
          throw new IllegalStateException(s"failed to commit $description")
        validateDataCommitted(fileSystem, finalPath, expectedManifest, Some(rowCount))
      } catch {
        case NonFatal(error) =>
          // Cleanup is restricted to the UUID generated by this invocation.
          if (fileSystem.exists(attemptPath)) fileSystem.delete(attemptPath, true)
          throw error
      }
    } finally if (!wasPersisted) stable.unpersist()
  }

  def writeManifest(fileSystem: FileSystem, directory: Path, contents: String): Unit = {
    val output = fileSystem.create(new Path(directory, CommitMarker), false)
    try output.write(contents.getBytes(StandardCharsets.UTF_8))
    finally output.close()
  }

  def validateCommitted(fileSystem: FileSystem, directory: Path, expectedManifest: String): Unit = {
    val marker = new Path(directory, CommitMarker)
    val success = new Path(directory, "_SUCCESS")
    if (!fileSystem.exists(marker) || !fileSystem.exists(success))
      throw new IllegalStateException(s"uncommitted or incomplete directory $directory")

    val input = fileSystem.open(marker)
    val actual = try {
      val source = scala.io.Source.fromInputStream(input, StandardCharsets.UTF_8.name())
      try source.mkString
      finally source.close()
    } finally {
      // Source.close closes the stream; Hadoop close is idempotent and keeps this safe if Source
      // construction or reading failed.
      input.close()
    }
    if (actual != expectedManifest)
      throw new IllegalStateException(s"commit identity mismatch for $directory")
  }

  def validateDataCommitted(
      fileSystem: FileSystem,
      directory: Path,
      expectedBase: String,
      expectedRowCount: Option[Long]
  ): Unit = {
    val marker = new Path(directory, CommitMarker)
    val success = new Path(directory, "_SUCCESS")
    if (!fileSystem.exists(marker) || !fileSystem.exists(success))
      throw new IllegalStateException(s"uncommitted or incomplete directory $directory")
    val input = fileSystem.open(marker)
    val source = scala.io.Source.fromInputStream(input, StandardCharsets.UTF_8.name())
    val actual = try source.mkString finally source.close()
    val lines = actual.linesIterator.toSeq
    if (lines.headOption.contains("version=1"))
      throw new IllegalStateException(
        "archive commit protocol pre-release v1 is unsupported; " +
          "pre-release v1 data must be regenerated as version 2")
    val rowCountLines = lines.filter(_.startsWith("row_count="))
    val rowCount = if (rowCountLines.size == 1)
      try rowCountLines.head.stripPrefix("row_count=").toLong
      catch { case _: NumberFormatException => -1L }
    else -1L
    val inventoryLines = lines.filter(_.startsWith("file=")).map(_.stripPrefix("file="))
    val inventory = inventoryLines.flatMap(parseInventoryEntry)
    val physicalInventory = parquetInventory(fileSystem, directory)
    val canonical = dataManifest(expectedBase, rowCount, physicalInventory)
    if (rowCount < 0L || inventory.size != inventoryLines.size ||
        inventory != physicalInventory || actual != canonical ||
        expectedRowCount.exists(_ != rowCount))
      throw new IllegalStateException(s"commit inventory mismatch for $directory")
  }

  def hasParquetData(fileSystem: FileSystem, path: Path): Boolean = {
    val files = fileSystem.listFiles(path, true)
    var found = false
    while (!found && files.hasNext) {
      found = files.next().getPath.getName.endsWith(".parquet")
    }
    found
  }

  private def dataManifest(
      base: String,
      rowCount: Long,
      files: Seq[ArchiveFileIdentity]
  ): String =
    base + s"row_count=$rowCount\n" + files.map { file =>
      s"file=${file.path}\t${file.size}\t${file.sha256}\n"
    }.mkString

  private def parquetInventory(
      fileSystem: FileSystem,
      directory: Path
  ): Seq[ArchiveFileIdentity] = {
    val qualifiedRoot = fileSystem.makeQualified(directory).toString.stripSuffix("/") + "/"
    val files = fileSystem.listFiles(directory, true)
    val found = scala.collection.mutable.ArrayBuffer.empty[ArchiveFileIdentity]
    while (files.hasNext) {
      val status = files.next()
      val path = fileSystem.makeQualified(status.getPath)
      if (path.getName.endsWith(".parquet"))
        found += ArchiveFileIdentity(
          path.toString.stripPrefix(qualifiedRoot), status.getLen, fileSha256(fileSystem, path))
    }
    found.sortBy(_.path)
  }

  private def fileSha256(
      fileSystem: FileSystem,
      path: Path
  ): String = {
    val digest = MessageDigest.getInstance("SHA-256")
    val input = fileSystem.open(path)
    val buffer = new Array[Byte](1024 * 1024)
    try {
      var read = input.read(buffer)
      while (read >= 0) {
        if (read > 0) digest.update(buffer, 0, read)
        read = input.read(buffer)
      }
    } finally input.close()
    digest.digest().map(byte => f"${byte & 0xff}%02x").mkString
  }

  private def parseInventoryEntry(value: String): Option[ArchiveFileIdentity] =
    value.split("\\t", -1).toSeq match {
      case Seq(path, size, sha256)
          if path.nonEmpty && sha256.matches("[0-9a-f]{64}") =>
        try {
          val parsedSize = size.toLong
          if (parsedSize >= 0L) Some(ArchiveFileIdentity(path, parsedSize, sha256)) else None
        } catch { case _: NumberFormatException => None }
      case _ => None
    }
}
